spring.application.name=logic-backend

python.backend.url=${PYTHON_BACKEND_URL}
ai-backend.url=${PYTHON_BACKEND_URL}

spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET:super-secret-key-that-is-long-enough-32b}
